config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'users#new'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/users/report', to: 'users#report'
  get '/users.csv', to: 'users#cvs' #remove this one?

  get 'users/q/*specs', controller: "users", action: "query"

  get '/users/export_to_csv', to: 'users#export_to_csv'
  get '/users/index', to: 'users#index'

  resources :users, only: [:index, :new, :create, :edit, :update, :show, :show_all, :welcome]
  resources :slots, only: [:index, :show, :new, :create, :edit, :update]
  resources :instructors, only: [:index, :show, :new, :create, :edit, :update]
  
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base

has_many :users

scope :teel, -> { where(id: '3') }

def name_with_email
	"#{name} #{email}"
end

end

app/models/slot.rb
class Slot < ActiveRecord::Base

has_many :users



end

app/models/user.rb
class User < ActiveRecord::Base
#include Sluggable

belongs_to :slot
belongs_to :instructor


has_secure_password validations: false

validates :email, presence: true, uniqueness: true
validates_length_of :email, :minimum => 7, :maximum => 7, :allow_blank => false, on: :create, :message => "is not requested.  Instead enter you Auburn UserID." 
validates :password, presence: true, on: :create, length: {minimum: 8}


 scope :short_list, -> { where(firstname: 'Sam') }


def update_slot_assigned_with_count(param)
  u = User.find(param)
  user_count = User.connection.select_all("SELECT * FROM users WHERE slot_id = #{u.slot_id}").count
  s = Slot.find(u.slot_id)
  s.assigned = user_count
  s.save
 
 # slot.assigned = User.where('slot_id == slot_id',"#{param}").count
  # The .where() method should be finding all rows containing the same value for "assigned"
  #    as passed by the form. It should then get the record count which becomes the
  #    value of slot.assigned
  # code below are some things tried out. 
  
	#binding.pry
  #slot.assigned = User.where('slot_id == slot_id',"#{param}").count
 
end  

  #sluggable_column :email

  def admin?
  	self.role == 'admin'
  end

  def moderator?
  	self.role == 'moderator'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  require 'csv'
  
  
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "Must be logged in to do that."
      redirect_to root_path
    end
  end

  def require_admin
    access_denied unless logged_in? and current_user.admin?
  end

  def access_denied
    flash[:error] = "You can't do that."
    redirect_to root_path
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :index]
	before_action :require_same_user, only: [:edit, :update, :index]
	before_action :require_admin, only: [:new, :create, :show, :edit, :update, :index]

	def index		 
	    @instructors = Instructor.all
	end

	def show
	 @instructor = Instructor.find(params[:id])
	end

	def new
		@instructor = Instructor.new
	end

	def create
		@instructor = Instructor.new(instructor_params)

		if @instructor.save
			flash[:notice] = "New instructor was successfully added."
			redirect_to :back
		else
			render :new
		end
	end

	def edit
		@instructor = Instructor.find(params[:id])
    end

	def update
		#binding.pry
		@instructor = Instructor.find(params[:id])
	  	if @instructor.update(instructor_params)
	      
	  		flash[:notice] = "This instructor has been updated."
	  		redirect_to instructor_path(@instructor)
	  	else
	  		render :edit
	  	end
	end

	private

	def instructor_params
		params.require(:instructor).permit(:name, :email)
	end

	def set_user
  		@user = User.find_by id: params[:id]
  	end

	def require_same_user
		if current_user != @current_user
		flash[:error] = "You're not allowed to do that."
		redirect_to root_path
	end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.where(email: params[:email]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you've logged in."
      redirect_to  edit_user_path(user.id)
    else
      flash[:error] = "I can't authenticate with this Auburn UserID and password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out."
    redirect_to login_path
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
	before_action :set_user, only: [:index, :show, :edit, :update]
	before_action :require_same_user, only: [:index, :show, :edit, :update]
	before_action :require_admin, only: [:index, :new, :create, :show, :edit, :update]

	def index		 
	    @slots = Slot.all
	end

	def show
	 @slot = Slot.find(params[:id])
	end

	def new
		@slot = Slot.new
	end

	def create
		@slot = Slot.new(slot_params)

		if @slot.save
			flash[:notice] = "New slot was successfully added."
			redirect_to :back
		else
			render :new
		end
	end

	def edit
		@slot = Slot.find(params[:id])
    end

	def update
		#binding.pry
		@slot = Slot.find(params[:id])
	  	if @slot.update(slot_params)
	      
	  		flash[:notice] = "This slot is updated."
	  		redirect_to slot_path(@slot)
	  	else
	  		render :edit
	  	end
	end

	private

	def slot_params
		params.require(:slot).permit(:description, :list_order, :assigned)
	end

	def set_user
  		@user = User.find_by id: params[:id]
  	end

	def require_same_user
		if current_user != @current_user
		flash[:error] = "You're not allowed to do that."
		redirect_to root_path
	end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :set_user, only: [:show, :edit, :update, :show_all]
   before_action :require_same_user, only: [:edit, :update, :show_all]
   before_action :require_admin, only: [:index, :report, :export_to_csv]

  def welcome    
  end

  def index   
  @users = User.all(:order => "lastname, firstname") 
  end

   def show   	
   end

   def show_all     
   end

   def query
    @users = User.where(Hash[*params[:specs].split("/")])
    #binding.pry
    if @users.empty?
      flash[error: "Can't find users with those properties"]      
     end
     render :index
   end

   def report
     @users = User.all(:order => "instructor_id")

      

    #@users = User.order(lastname: :asc).take(500)
    #@users = User.find(:all, :order => "lastname, firstname")
    #@users = User.all(:order => "instructor_id")
    #@users = User.where(firstname: true)
    #@users = User.take(500).order(:created_at)  

   end


def export_to_csv       
    @users = User.all(:order => "instructor_id")
    csv_string = CSV.generate do |csv|
         csv << ["First Name", "Last Name", "Email", "Description","Instructor"]
         @users.each do |user|
           csv << [user.firstname, user.lastname, user.email,  user.slot.description, user.instructor.name]
         end
    end         
  
   send_data csv_string,
   :type => 'text/csv; charset=iso-8859-1; header=present',
   :disposition => "attachment; filename=users.csv" 
end 


  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	 
  	if @user.save
  		session[:user_id] = @user.id
  		flash[:notice] = "You have successfully registered!"
  		redirect_to edit_user_path(@user)
  	else
  		render :new
    end
  end

  def edit;
  end

  def update
  	if @user.update(user_params)
       current_user.update_slot_assigned_with_count(params[:id])
      #binding.pry
      AppMailer.welcome_email(@user).deliver
  		flash[:notice] = "#{@user.firstname} #{@user.lastname}, your seat is reserved for #{@user.slot.description}."
  		redirect_to user_path(@user)
  	else
  		render :edit
  	end
  end


  private

  def user_params
  		params.require(:user).permit(:role, :firstname, :lastname, :email, :password, :instructor_id, :slot_id)
  	end

  	def set_user
  		@user = User.find_by id: params[:id]
  	end

  	def require_same_user #but allow admin
  		if ! current_user.admin? && current_user != @user
  		flash[:error] = "You're not allowed to do that."
  		redirect_to root_path
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def slot_assigned_less_than_thirty
	 	Slot.where('assigned <= 25').order('list_order asc')
	end


end

app/views/instructors/_form.html.erb
<div class="container-fluid">
<div class='well'>
  <%= form_for @instructor do |f| %>
  <%= render 'shared/errors', obj: @instructor %>
    <div class='control-group'>
      <%= f.label :name, 'Example: Smith, Joe' %><br>
      <%= f.text_field :name %>
    </div>
    <br>
    <div class='control-group'>
      <%= f.label :email, 'Auburn email address' %><br>
      <%= f.text_field :email %>
    </div>
     <br><br>
    <%= f.submit (@instructor.new_record? ? "Add instructor" : "Update instructor"), class: 'btn btn-success' %>
  <% end %>
</div>
</div>

app/views/instructors/edit.html.erb
<%= render 'shared/content_title', title: 'Edit an Instructor' %>

<%= render 'form' %>

app/views/instructors/index.html.erb
<div class="container-fluid">
<div class='nav_item'>
    <%= link_to 'New Instructor', new_instructor_path, class: 'btn btn-success btn-small' %>
  </div>

   <h1>Listing instructors</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>       
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.name %></td>
        <td><%= instructor.email %></td>         
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
         
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>
</div>

app/views/instructors/new.html.erb
<%= render 'shared/content_title', title: 'Add an Instructor' %>

<%= render 'form' %>

app/views/instructors/show.html.erb
<div class="container-fluid">
<div class='nav_item'>
    <%= link_to 'New Instructor', new_instructor_path, class: 'btn btn-success btn-small' %>
  </div>

   <h1>Show instructor</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
     
      <tr>
        <td><%= @instructor.name %></td>
        <td><%= @instructor.email %></td>
        <td><%# link_to 'Edit', edit_slot_path(@slot) %>
          <%= link_to edit_instructor_path(@instructor) do %>
              Edit <i class='icon-pencil'></i>
           <% end %>
        </td>         
      </tr>
    
  </tbody>
</table>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div class="container-fluid">
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
</div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to 'COMM1000 & COMM1003 Final Exam Reservation', root_path, :class => 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  
      <ul class="nav navbar-nav">
        <% if logged_in? and current_user.admin? %>
        <li class='dropdown'>
          <%= link_to('', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-expanded' => 'false') do %>
          <%= 'Slots' %>
          <span class='caret'></span>
          <% end %>
          <ul class='dropdown-menu', 'role' = 'menu'>
            <li>
              <%= link_to 'Slots index', slots_path %>
            </li> 
            <li>
              <%= link_to 'New Slot', new_slot_path %>
            </li>
          </ul>


          <li class='dropdown'>
          <%= link_to('', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-expanded' => 'false') do %>
          <%= 'Instructor' %>
          <span class='caret'></span>
          <% end %>
          <ul class='dropdown-menu', 'role' = 'menu'>
            <li>
              <%= link_to 'Instructors index', instructors_path %>
            </li> 
            <li>
              <%= link_to 'New Instructor', new_instructor_path %>
            </li>
          </ul>


          <li class='dropdown'>
          <%= link_to('', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-expanded' => 'false') do %>
          <%= 'Reports' %>
          <span class='caret'></span>
          <% end %>
          <ul class='dropdown-menu', 'role' = 'menu'>
            <li>
              <%= link_to 'Students and Day-Time Slots by Instructor', users_report_path %>
            </li> 
            <li>
              <%= link_to 'Export Users CSV', users_export_to_csv_path %>
            </li>
          </ul>

        
        <% end %>
        <% if logged_in? %> 
        <li class='dropdown'>
          <%= link_to('', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-expanded' => 'false') do %>
          <%= current_user.email %>
          <span class='caret'></span>
          <% end %>
          <ul class='dropdown-menu', 'role' = 'menu'>
            <li>
              <%= link_to edit_user_path(current_user) do %>
              <i class='icon-pencil'></i>
              Edit my reservation
              <% end %>
            </li>
           
            <li>
              <%= link_to logout_path do %>
              <i class='icon-circle-arrow-left'></i>
              logout
              <% end %>
            </li>

            <% else # logged out%>

             <li>
              <%= link_to 'Log in', login_path, class: 'btn btn-small' %>
             
            <% end %>
          </li>
          
        </ul>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>COMM 1000 Final Exam Reservation</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/index.html.erb
<h3>Welcome!</h3>

<p>This is the Postit template. You've access the PostsController, index action. This is the index template. Find me under app/views/posts folder.</p>

app/views/shared/_content_title.html.erb
<div class="container-fluid">
<h1>
	<%= title %>
	 
</h1>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class= 'row'>
		<div class='alert alert-error span8'>
			<h5> There were some errors: </h5>
			<ul>
				<% obj.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/slots/_form.html.erb
<div class="container-fluid">
<div class='well'>
  <%= form_for @slot do |f| %>
  <%= render 'shared/errors', obj: @slot %>
    <div class='control-group'>
      <%= f.label :description, 'Example: (Monday, April 6, 5:00pm)' %><br>
      <%= f.text_field :description, :size => 40 %>
    </div>
    <br>
    <div class='control-group'>
      <%= f.label :list_order, 'An integer value to indicate position in the list' %><br>
      <%= f.text_field :list_order, :size => 3 %>
    </div>
     <br>
    <div class='control-group'>
      <%= f.label :assigned, 'Number of reservations choosing this slot' %><br>
      <%= f.text_field :assigned, :size => 3 %>
    </div>
     <br><br>
    <%= f.submit (@slot.new_record? ? "Add Slot" : "Update Slot"), class: 'btn btn-success' %>
  <% end %>
</div>
</div>

app/views/slots/edit.html.erb
<%= render 'shared/content_title', title: 'Edit a Slot' %>

<%= render 'form' %>

 

app/views/slots/index.html.erb
<div class="container-fluid">
<div class='nav_item'>
    <%= link_to 'New Slot', new_slot_path, class: 'btn btn-success btn-small' %>
  </div>

   <h1>Listing slots</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Description</th>
      <th>list_order</th>
      <th>assigned</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.description %></td>
        <td><%= slot.list_order %></td>
        <td><%= slot.assigned %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
         
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot', new_slot_path %>
</div>

app/views/slots/new.html.erb
<%= render 'shared/content_title', title: 'Add a Slot' %>

<%= render 'form' %>

app/views/slots/show.html.erb
<div class='nav_item'>
    <%= link_to 'New Slot', new_slot_path, class: 'btn btn-success btn-small' %>
  </div>

   <h1>Listing slots</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>list_order</th>
      <th>assigned</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.description %></td>
        <td><%= slot.list_order %></td>
        <td><%= slot.assigned %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
         
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot', new_slot_path %>

app/views/users/cvs.html.erb
 <%- headers = ['Firstname', 'Lastname', 'Email', 'Slot Description', 'Instructor'] -%>
<%= CSV.generate_line headers %>
<%- @users.each do |user| -%>
  <%= CSV.generate_line([user.firstname, user.lastname, user.email, user.slot.description, user.instructor.name]) %>
<%- end -%> 

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Complete  Reservation" %>
 
<div class='container-fluid'>
<div class='well'>	
  <%= form_for @user do |f| %>
  <%= render 'shared/errors', obj: @user %>


<%=  f.label "Select a Day and Time" %>    
    <%= f.select("slot_id", slot_assigned_less_than_thirty.collect {|s| [ s.description, s.id ] }) %>
    <br /><br />

<%=  f.label "Select your instructor" %>    
    <%= f.select("instructor_id", Instructor.all(:order => "name").collect   {|i| [ i.name, i.id ] }) %>
    <br /><br />
     
    <%  if logged_in? and current_user.admin? %>       
     <div class='control-group'>
      <%= f.label :role, 'Role' %><br>
      <%= f.text_field :role %>
     </div>
     <div class='control-group'>
      <%= f.label :email, 'Your Auburn UserID (7 characters)' %><br> 
      <%= f.text_field :email %>
     </div>
     <br /><br />
    <% end %>
    
    <%= f.submit (@user.new_record? ? "Register" : "Complete my reservation"), class: 'btn btn-success' %>
  <% end %>
 
  </div>
</div>
 

app/views/users/export_to_csv.html.erb
<%= render 'shared/content_title', title:  "Report Page"  %>
<div class="container-fluid">
<div class='well'>

 <%# @users %>

<h3>Students and DayTime Slots by Instructor</h3>
<% @users.each do |u| %>
<div class="row">
	<div class="col-md-2">
		<%= u.firstname %>
		<%= u.lastname %>
	</div>

	<div class="col-md-2">	
		<%= u.email %>		 
	</div>	

	  <div class="col-md-2">	
		<%= u.id %>		 
	</div>	 

</div>
<% end %>
      <hr />

 
  


</div>
</div>

app/views/users/index.html.erb
<div class="container-fluid">
<div class='nav_item'>
    <%= link_to 'New User', new_user_path, class: 'btn btn-success btn-small' %>
  </div>

   <h1>Listing users</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>email</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
         
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>

<div class="container-fluid">
<div class='well'>
  <%= form_for @user do |f| %>
  <%= render 'shared/errors', obj: @user %>
    <div class='control-group'>
      <%= f.label :firstname, 'First name' %><br>
      <%= f.text_field :firstname %>
    </div>
    <br>
    <div class='control-group'>
      <%= f.label :lastname, 'Last name' %><br>
      <%= f.text_field :lastname %>
    </div>
    <br>
    <div class='control-group'>
      <%= f.label :email, 'Your Auburn UserID (7 characters)' %><br> 
      <%= f.text_field :email %>
    </div>
    <br>
    <div class='control-group'>
      <%= f.label :password %><br>
      <%= f.password_field :password %><br><br>
    </div>
    <%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: 'btn btn-success' %>
  <% end %>
  Already registered? <%= link_to login_path do %>
           
          login
        <% end %>
</div>
</div>

app/views/users/report.html.erb
<%= render 'shared/content_title', title:  "Students and Day-Time Slots by Instructor"  %>
<div class="container-fluid">
<div class='well'>


 <%= @users %>

<% assigned = [] %>
<% @users.each do |u| %>
<% assigned << u.slot.assigned %>
<% end %>
<%= assigned %>

<hr />
<% description = [] %>
<% @users.each do |u| %>
<% description << u.slot.description %>
<% end %>
<%= desc_list = description.to_s.gsub(/"/,"'") %>


<% @users.each do |u| %>
<div class="row">
	<div class="col-md-2">
		<%= u.firstname %>
		<%= u.lastname %>
	</div>

	<div class="col-md-2">	
		<%= u.slot.description %>		 
	</div>	

	<div class="col-md-1">	
		<%= u.slot.assigned %>		 
	</div>	

	  <div class="col-md-2">	
		<%= u.instructor.name %>		 
	</div>	 

</div>
<% end %>
      <hr />

  <% myarray = @users.to_a %>
  <%# myarray %>    
  <hr />
<%= User.short_list %>>

  <hr />

<script type="text/javascript">
$(function() {
	$('#chart_container').highcharts({
		chart: {
			type: 'bar'
		},
		title: {
			text: "Day-Time Slot Reservation Counts"
		},
		xAxis: {
			categories: ['Monday, April 6, 5:00pm', 'Monday, April 6, 5:30pm', 'Monday, April 6, 6:00pm', 'Monday, April 6, 7:00pm', 'Monday, April 6, 7:30pm', 'Tuesday, April 7, 6:30pm',] // 	//user.slot.description		<%= description.to_s.gsub(/"/,"'") %>   <%= desc_list %>
		},
		yAxis: {
			title: {
				text: "Number of Reservations"
			}
		},
		series: [{
			data:  <%= assigned %>//[5,2,2,1,1,1] //user.slot.assigned
		}]
	});
});
</script>
  <div id="chart_container" style="width:560px; height:300px;"></div>


  <%= link_to 'Download Students and Day-Time Slots by Instructor CSV', users_export_to_csv_path %>  

  
 
</div>
</div>


 

 

app/views/users/show.html.erb
<div class="container-fluid">
<%= render 'shared/content_title', title:  "Thanks for reserving a seat at the COMM1000 and COMM1003 Final Exam"  %>

	<div class='well'>
		
		<p>You will receive an email confirmation. <%= link_to "Edit my reservation", edit_user_path(current_user) %> </p>
		
	</div>
</div>

app/views/users/show_all.html.erb
<%= render 'shared/content_title', title:  "Show All Page"  %>

<div class='well'>
 
  
        
</div>

app/views/users/welcome.html.erb
<div class="container-fluid">
<%= render 'shared/content_title', title:  "Thanks for reserving a seat at the COMM1000 and COMM1003 Final Exam"  %>

	<div class='well'>
		
		<p>You will receive an email confirmation. <%= link_to "Edit my reservation", edit_user_path(current_user) %> </p>
		
	</div>
</div>